/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programa_matrices;

import funciones_matrices.diferencia_matrices;
import funciones_matrices.suma_matrices;
import javax.swing.JOptionPane;

/**
 *
 * @author edson
 */
public class MatriceSGUI extends javax.swing.JFrame {

    /**
     * Creates new form MatriceSGUI
     */
    public MatriceSGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_tami = new javax.swing.JTextField();
        bres = new javax.swing.JLabel();
        btnsum = new javax.swing.JButton();
        txt_tamj = new javax.swing.JTextField();
        btnres = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnsum.setText("Cacuar Suma");
        btnsum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumActionPerformed(evt);
            }
        });

        btnres.setText("Cacuar Resta");
        btnres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(bres, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tami, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tamj, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnres)
                            .addComponent(btnsum))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsum)
                    .addComponent(txt_tami, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tamj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnres))
                .addGap(40, 40, 40)
                .addComponent(bres, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumActionPerformed
      int tami, tamj;
      double[][] matriz1,matriz2;
      tami=Integer.parseInt(txt_tami.getText());
      tamj=Integer.parseInt(txt_tamj.getText());
      matriz1=new double[tami][tamj];
      matriz2= new double[tami][tamj];
        for (int i = 0; i < tami; i++) {
            for (int j = 0; j < tamj; j++) {
                matriz1[i][j]=Double.valueOf(JOptionPane.showInputDialog("Matriz Uno"));
            }
        }
        for (int i = 0; i < tami; i++) {
            for (int j = 0; j < tamj; j++) {
                matriz2[i][j]=Double.valueOf(JOptionPane.showInputDialog("Matriz Dos"));
            }
        }
        for (int i = 0; i < tami; i++) {
            for (int j = 0; j < tamj; j++) {
                System.out.println(matriz1[i][j] + "-");
            }
            System.out.println("\n");
        }
        suma_matrices suma = new suma_matrices();
        suma.SumaMatrices(matriz1, matriz2, tami, tamj);
    }//GEN-LAST:event_btnsumActionPerformed

    private void btnresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresActionPerformed
         int tami, tamj;
      double[][] matriz1,matriz2;
      tami=Integer.parseInt(txt_tami.getText());
      tamj=Integer.parseInt(txt_tamj.getText());
      matriz1=new double[tami][tamj];
      matriz2= new double[tami][tamj];
        for (int i = 0; i < tami; i++) {
            for (int j = 0; j < tamj; j++) {
                matriz1[i][j]=Double.valueOf(JOptionPane.showInputDialog("Matriz Uno"));
            }
        }
        for (int i = 0; i < tami; i++) {
            for (int j = 0; j < tamj; j++) {
                matriz2[i][j]=Double.valueOf(JOptionPane.showInputDialog("Matriz Dos"));
            }
        }
         diferencia_matrices diferencia = new diferencia_matrices();
        diferencia.DiferenciaMatrices(matriz1, matriz2, tami, tamj);
        for (int i = 0; i < tami; i++) {
            for (int j = 0; j < tamj; j++) {
                System.out.println(matriz1[i][j] + "-");
                bres.setText(bres.getText() +"\t" + diferencia.DiferenciaMatrices(matriz1, matriz2, tami, tamj) );
            }
            System.out.println("\n");
            bres.setText(bres.getText() + "\n");
        }
       
    }//GEN-LAST:event_btnresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatriceSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatriceSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatriceSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatriceSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatriceSGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bres;
    private javax.swing.JButton btnres;
    private javax.swing.JButton btnsum;
    private javax.swing.JTextField txt_tami;
    private javax.swing.JTextField txt_tamj;
    // End of variables declaration//GEN-END:variables
}
